on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - name: Installl Firefox
      run: sudo apt-get install firefox
    - run: yarn
    - run: yarn run build
    - run: yarn run build:test
    - run: yarn run test:firefox:headless
